const ActionTypes = {
  FILTER_CATEGORIES: 'FILTER_CATEGORIES',
  DELETE_MOVIE: 'DELETE_MOVIE',
  SET_MOVIES_PER_PAGE: 'SET_MOVIES_PER_PAGE',
  NEXT_PAGE: 'NEXT_PAGE',
  PREVIOUS_PAGE: 'PREVIOUS_PAGE',
  LIKE_MOVIE: 'LIKE_MOVIE',
  DISLIKE_MOVIE: 'DISLIKE_MOVIE'
};

export default ActionTypes;
